# Generated by Django 4.2.16 on 2024-09-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.CharField(default='1', max_length=212),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Process'), (2, 'Completed'), (3, 'Cancelled')]),
        ),
    ]
